# Afficher les informations d'un utilisateur
GET https://medocvit.onrender.com/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJlbW1ldHQuYnJvd25AZ21haWwuY29tIiwiaWF0IjoxNzQ3NDk1ODgzLCJleHAiOjE3NDc1ODIyODN9.xDlYjpucWQAFV6DrLY00PYj7p_uaY5NJj0R2t8GiiS8


# 1. Créer une route permettant de créer un utilisateur
### Créer un user
POST https://medocvit.onrender.com/api/auth/local/register
Content-Type: application/json

{
  "data": {
    "email": "marty.mcfly@example.com",
    "password": "martymcfly123",
    "first_name": "Marty",
    "last_name": "McFly",
    "gender": "Homme",
    "birth_date": "1990-03-03"
  }
}


# Créer une route permettant de se connecter avec un utilisateur en renvoyant un token JWT
### Créer un user
POST https://medocvit.onrender.com/api/auth/local
Content-Type: application/json

{
    "data": {
        "email": "john.doe@example.com",
        "password": "johndoe123"
    }
}

